// angular/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent implements OnInit {
  newItemName: string = '';
  newItemStatus: string = 'pending';
  newItemDuration: number = 0;
  newItemLocation: string = '';
  items: any[] = [];
  selectedStatusFilter: string = 'all';

  ngOnInit() {
    const storedItems = localStorage.getItem('items');
    if (storedItems) {
      this.items = JSON.parse(storedItems);
    }
  }

  addItem() {
    const newItem = {
      name: this.newItemName,
      status: this.newItemStatus,
      startTime: new Date(),
      endTime: new Date(),
      duration: this.newItemDuration,
      location: this.newItemLocation,
      isEditing: false,
    };

    this.items.push(newItem);

    this.newItemName = '';
    this.newItemStatus = 'pending';
    this.newItemDuration = 0;
    this.newItemLocation = '';

    localStorage.setItem('items', JSON.stringify(this.items));
  }

  viewLocationOnMap(location: string) {
    // You can use the Google Maps API for this purpose
    window.open(`https://maps.google.com/maps?q=${location}&output=embed`);
  }

  exportToCSV() {
    const csvData = this.convertItemsToCSV(this.items);
    const blob = new Blob([csvData], { type: 'text/csv' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'items.csv';
    a.click();
    window.URL.revokeObjectURL(url);
  }

  convertItemsToCSV(items: any[]): string {
    const header = [
      'Name',
      'Status',
      'Start Time',
      'End Time',
      'Duration',
      'Location',
    ];
    const rows = items.map((item) => [
      item.name,
      item.status,
      item.startTime,
      item.endTime,
      item.duration,
      item.location,
    ]);
    return [header, ...rows].map((e) => e.join(',')).join('\n');
  }

  editItem(index: number) {
    this.items[index].isEditing = true;
  }

  updateItem(index: number) {
    this.items[index].isEditing = false;
    localStorage.setItem('items', JSON.stringify(this.items));
  }

  cancelEdit(index: number) {
    this.items[index].isEditing = false;
  }

  deleteItem(index: number) {
    this.items.splice(index, 1);
    localStorage.setItem('items', JSON.stringify(this.items));
  }

  get filteredItems() {
    if (this.selectedStatusFilter === 'all') {
      return this.items;
    } else {
      return this.items.filter(
        (item) => item.status === this.selectedStatusFilter
      );
    }
  }
}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>To-Do List</title>

    <!-- Include Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    />

    <!-- Include the CSS you provided -->
    <link rel="stylesheet" href="app.component.css" />
  </head>

  <body>
    <div class="container mt-4">
      <h1 class="text-center">To-Do List</h1>
      <div
        id="map-popup"
        style="display: none; width: 100%; height: 400px"
      ></div>
      <!-- Form to add a new item -->
      <form (ngSubmit)="addItem()" #addItemForm="ngForm">
        <div class="form-group">
          <label for="itemName">Name:</label>
          <input
            type="text"
            id="itemName"
            class="form-control"
            required
            [(ngModel)]="newItemName"
            name="newItemName"
          />
        </div>
        <div class="form-group">
          <label for="status">Status:</label>
          <select
            id="status"
            class="form-control"
            required
            [(ngModel)]="newItemStatus"
            name="newItemStatus"
          >
            <option value="pending">Pending</option>
            <option value="doing">Doing</option>
            <option value="done">Done</option>
          </select>
        </div>
        <div class="form-group">
          <label for="duration">Duration (minutes):</label>
          <input
            type="number"
            id="duration"
            class="form-control"
            required
            [(ngModel)]="newItemDuration"
            name="newItemDuration"
          />
        </div>
        <div class="form-group">
          <label for="location">Location:</label>
          <input
            type="text"
            id="location"
            class="form-control"
            [(ngModel)]="newItemLocation"
            name="newItemLocation"
          />
        </div>
        <button type="submit" class="btn btn-primary">Add Item</button>
      </form>

      <!-- Filter items by status -->
      <div class="mt-3">
        <label for="statusFilter">Filter by Status:</label>
        <select
          id="statusFilter"
          class="form-control"
          [(ngModel)]="selectedStatusFilter"
        >
          <option value="all">All</option>
          <option value="pending">Pending</option>
          <option value="doing">Doing</option>
          <option value="done">Done</option>
        </select>
      </div>
      <button class="btn btn-success" (click)="exportToCSV()">
        Export to CSV
      </button>
    </div>

    <!-- Table to display items -->
    <div class="container mt-3 text-center">
      <table class="table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Start Time</th>
            <th>End Time</th>
            <th>Duration (minutes)</th>
            <th>Status</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let item of filteredItems; let i = index">
            <td *ngIf="!item.isEditing">{{ item.name }}</td>
            <td *ngIf="!item.isEditing">
              {{ item.startTime | date : "medium" }}
            </td>
            <td *ngIf="!item.isEditing">
              {{ item.endTime | date : "medium" }}
            </td>
            <td *ngIf="!item.isEditing">{{ item.duration }}</td>
            <td *ngIf="!item.isEditing">{{ item.status }}</td>
            <td *ngIf="!item.isEditing">
              <button class="btn btn-primary" (click)="editItem(i)">
                Edit
              </button>
              <button class="btn btn-danger" (click)="deleteItem(i)">
                Delete
              </button>
              <button
                class="btn btn-info"
                (click)="viewLocationOnMap(item.location)"
                data-toggle="modal"
                data-target="#locationModal"
              >
                View Location
              </button>
            </td>
            <td *ngIf="item.isEditing">
              <input [(ngModel)]="item.name" />
            </td>
            <td *ngIf="item.isEditing">
              <input type="number" [(ngModel)]="item.duration" />
            </td>
            <td *ngIf="item.isEditing">
              <select [(ngModel)]="item.status">
                <option value="pending">Pending</option>
                <option value="doing">Doing</option>
                <option value="done">Done</option>
              </select>
            </td>
            <td *ngIf="item.isEditing">
              <button class="btn btn-success" (click)="updateItem(i)">
                Update
              </button>
              <button class="btn btn-warning" (click)="cancelEdit(i)">
                Cancel
              </button>
            </td>
          </tr>
        </tbody>
      </table>
    </div>

    <!-- Modal for displaying the location -->
    <div class="modal fade" id="locationModal" tabindex="-1" role="dialog">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">Location Map</h5>
            <button
              type="button"
              class="close"
              data-dismiss="modal"
              aria-label="Close"
            >
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <div id="map-popup" style="width: 100%; height: 400px"></div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

// VueList/src/App.vue
<template>
  <div class="container mt-4">
    <h1 class="text-center">To-Do List</h1>

    <!-- Form to add a new item -->
    <form @submit.prevent="addItem" class="mb-4">
      <div class="form-group">
        <label for="itemName">Name:</label>
        <input
          v-model="newItem.name"
          type="text"
          id="itemName"
          class="form-control"
          required
        />
      </div>
      <div class="form-group">
        <label for="status">Status:</label>
        <select
          v-model="newItem.status"
          id="status"
          class="form-control"
          required
        >
          <option value="pending">Pending</option>
          <option value="doing">Doing</option>
          <option value="done">Done</option>
        </select>
      </div>
      <div class="form-group">
        <label for="duration">Duration (in minutes):</label>
        <input
          v-model="newItem.duration"
          type="number"
          id="duration"
          class="form-control"
          required
          @input="resetNegativeDuration"
        />
      </div>
      <div class="form-group">
        <label for="location">Location:</label>
        <input
          v-model="newItem.location"
          type="text"
          id="location"
          class="form-control"
        />
      </div>
      <button type="submit" class="btn btn-primary">Add Item</button>
    </form>

    <!-- Filter by Status -->
    <div class="form-group">
      <label for="filterStatus">Filter by Status:</label>
      <select v-model="selectedStatus" id="filterStatus" class="form-control">
        <option value="all">All</option>
        <option value="pending">Pending</option>
        <option value="doing">Doing</option>
        <option value="done">Done</option>
      </select>
    </div>

    <button @click="exportToCSV" class="btn btn-success">Export to CSV</button>

    <!-- Table to display items -->
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Duration (minutes)</th>
          <th>Start Time</th>
          <th>End Time</th>
          <th>Status</th>
          <th>edit</th>
          <th>delete</th>
          <th>view</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="(item, index) in filteredItems" :key="index">
          <td>{{ item.name }}</td>
          <td>{{ item.duration }}</td>
          <td>{{ item.startTime }}</td>
          <td>{{ item.endTime }}</td>
          <td>{{ item.status }}</td>
          <td>
            <button @click="removeItem(index)" class="btn btn-danger btn-lg">
              Remove
            </button>
          </td>
          <td>
            <button @click="startEditing(index)" class="btn btn-primary btn-lg">
              Edit
            </button>
          </td>
          <td>
            <button
              @click="viewLocation(item.location)"
              class="btn btn-info btn-lg"
            >
              View Location
            </button>
          </td>
        </tr>
      </tbody>
    </table>

    <!-- Include the EditItem component with v-if when editing is required -->
    <EditItem
      v-if="editingIndex !== null"
      :item-to-edit="items[editingIndex]"
      @save-changes="saveEditedItem"
    />
  </div>

  <!-- View Location Modal -->
  <div
    class="modal fade"
    id="viewLocationModal"
    tabindex="-1"
    role="dialog"
    aria-labelledby="viewLocationModalLabel"
    aria-hidden="true"
  >
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="viewLocationModalLabel">Location</h5>
          <button
            type="button"
            class="close"
            data-dismiss="modal"
            aria-label="Close"
          >
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body" id="mapContainer">
          <iframe width="100%" height="400" :src="googleMapsUrl"></iframe>
        </div>
        <div class="modal-footer">
          <button
            type="button"
            id="closeViewLocationModalButton"
            class="btn btn-secondary"
            data-dismiss="modal"
            @click="closeViewLocationModal"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from "vue";
import EditItem from "./views/EditItem.vue";
const GOOGLE_MAPS_API_KEY = "YOUR_API_KEY"; // Replace with your Google Maps API key

const items = ref([]);
const newItem = ref({
  name: "",
  status: "pending",
  duration: 0,
  location: "",
});
const selectedStatus = ref("all");
const editingIndex = ref(null);

const filteredItems = computed(() => {
  if (selectedStatus.value === "all") {
    return items.value;
  } else {
    return items.value.filter((item) => item.status === selectedStatus.value);
  }
});

onMounted(() => {
  const savedItems = localStorage.getItem("todoItems");
  if (savedItems) {
    items.value = JSON.parse(savedItems);
  }
});

function resetNegativeDuration() {
  if (newItem.value.duration < 0) {
    alert("Duration must be a positive number.");
    newItem.value.duration = 0;
  }
}

function addItem() {
  newItem.value.startTime = new Date().toLocaleTimeString();
  newItem.value.endTime = calculateEndTime(newItem.value);
  items.value.push({ ...newItem.value });
  newItem.value.name = "";
  newItem.value.duration = 0;
  newItem.value.location = "";
  saveItems();
}

function removeItem(index) {
  items.value.splice(index, 1);
  saveItems();
}

function calculateEndTime(item) {
  const startTime = new Date();
  const endTime = new Date(startTime.getTime() + item.duration * 60 * 1000);
  return endTime.toLocaleTimeString();
}

function startEditing(index) {
  editingIndex.value = index;
}

function saveEditedItem(updatedItem) {
  if (editingIndex.value !== null) {
    items.value[editingIndex.value] = { ...updatedItem };
    editingIndex.value = null;
    saveItems();
  }
}

function viewLocation(location) {
  const googleMapsUrl = `https://maps.google.com/maps?q=${location}&output=embed`;
  const viewLocationModal = document.getElementById("viewLocationModal");
  viewLocationModal.classList.add("show");
  newItem.value.location = location;
}

function closeViewLocationModal() {
  const viewLocationModal = document.getElementById("viewLocationModal");
  viewLocationModal.classList.remove("show");
}

function saveItems() {
  localStorage.setItem("todoItems", JSON.stringify(items.value));
}

const googleMapsUrl = computed(() => {
  return `https://maps.google.com/maps?q=${newItem.value.location}&output=embed`;
});

// Function to export data to CSV
function exportToCSV() {
  const csvData = items.value.map((item) => {
    return `${item.name},${item.duration},${item.startTime},${item.endTime},${item.status},${item.location}`;
  });
  csvData.unshift("Name,Duration,Start Time,End Time,Status,Location");
  const csvContent = "data:text/csv;charset=utf-8," + csvData.join("\n");
  const encodedUri = encodeURI(csvContent);
  const link = document.createElement("a");
  link.setAttribute("href", encodedUri);
  link.setAttribute("download", "todo_items.csv");
  link.style.display = "none";
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}
</script>

<style scoped>
/* Your CSS styles here */
.container {
  max-width: 800px;
  margin: 0 auto;
}

h1 {
  font-size: 28px;
  text-align: center;
  margin-bottom: 20px;
}

.form-group {
  margin-bottom: 20px;
}

.form-control {
  border-radius: 10px;
}

.btn-primary {
  background-color: #007bff;
  color: #fff;
  border: none;
}

.btn-danger {
  background-color: #dc3545;
  color: #fff;
  border: none;
}

.btn-info {
  background-color: #17a2b8;
  color: #fff;
  border: none;
}

.table {
  margin-top: 20px;
  width: 50rem;
}

table th {
  background-color: #f5f5f5;
}

table th,
table td {
  text-align: center;
}

table td {
  vertical-align: middle;
}

.modal-content {
  position: relative;
}
</style>
